export const GET_NETFLIX = "GET_NETFLIX";
export const GET_TOP_NETFLIX = "GET_TOP_NETFLIX";
export const GET_ACTION_NETFLIX = "GET_ACTION_NETFLIX";
export const GET_COMEDY_NETFLIX = "GET_COMEDY_NETFLIX";
export const GET_HORROR_NETFLIX = "GET_HORROR_NETFLIX";
export const GET_DOCUMENT_NETFLIX = "GET_DOCUMENT_NETFLIX";
export const GET_TRENDING_NETFLIX = "GET_TRENDING_NETFLIX";
export const GET_MOVIE_SEARCH = "GET_MOVIE_SEARCH";

export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL";
